version: "1.0"
services:
  fastapi:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /home/gil/Desktop/class_files:/data/class_files  # Data directory for file storage
      - ./app:/app 
      - /var/run/docker.sock:/var/run/docker.sock # Docker socket for docker in docker
    command: uvicorn server:app --host 0.0.0.0 --port 8000
    extra_hosts:
    - "host.docker.internal:host-gateway" # Docker internal host address